const productos = [
    {
        id: 1,
        nombre: "Ladrillo Hueco",
        medida:"08x18x33" ,
        marca:"Franelli" ,
        precio: "$400",
        tipoConstruccion:"Tradicional",
    },
    {
        id:2,
        nombre: "Ladrillo Comun",
        medida:"25x12x5" ,
        marca:"Don Tino" ,
        precio: "$148",
        tipoConstruccion:"Tradicional",
    },
    {
        id:3,
        nombre: "Ladrillo Hueco",
        medida:"12x18x33" ,
        marca:"Franelli" ,
        precio: "$515",
        tipoConstruccion:"Tradicional",
    },
    {
        id:4,
        nombre: "Ladrillo Hueco",
        medida:"18x18x33" ,
        marca:"Franelli" ,
        precio: "$755",
        tipoConstruccion:"Tradicional",
    },
    {
        id:5,
        nombre: "Cemento",
        medida:"50 kg" ,
        marca:"Hidralit" ,
        precio: "$8.690",
        tipoConstruccion:"Tradicional",
    },
    {
        id:6,
        nombre: "Cemento",
        medida:"50 kg" ,
        marca:"Loma Negra" ,
        precio: "$9.065",
        tipoConstruccion:"Tradicional",
    },
    {
        id:7,
        nombre: "Cal Hidratada",
        medida:"25 kg" ,
        marca:"Hidralit" ,
        precio: "$4.035",
        tipoConstruccion:"Tradicional",
    },
    {
        id:8,
        nombre: "Cal Hidratada",
        medida:"30 kg" ,
        marca:"Cacique" ,
        precio: "$6.062",
        tipoConstruccion:"Tradicional",
    },
    {
        id:9,
        nombre: "Bolsa de Arena Fina",
        medida:"20 dm3" ,
        marca:"Easy" ,
        precio: "$2.725",
        tipoConstruccion:"Tradicional",
    },
    {
        id:10,
        nombre: "Bolsa de Arena Gruesa",
        medida:"20 dm3" ,
        marca:"Easy" ,
        precio: "$1.340",
        tipoConstruccion:"Tradicional",
    },
    {
        id:11,
        nombre: "Bolsón de Arena",
        medida:"1 m3" ,
        marca:"Easy" ,
        precio: "$33.840",
        tipoConstruccion:"Tradicional",
    },
    {
        id:12,
        nombre: "Placa de Yeso 9.5",
        medida:"1.20x2.40 m" ,
        marca:"Maxhaus" ,
        precio: "$12.950",
        tipoConstruccion:"En Seco",
    },
    {
        id:13,
        nombre: "Placa de Yeso 12.5",
        medida:"1.20x2.40 m" ,
        marca:"Maxhaus" ,
        precio: "$13.590",
        tipoConstruccion:"En Seco",
    },
    {
        id:14,
        nombre: "Montante 34",
        medida:"50Px12x2.60 m" ,
        marca:"Maxhaus" ,
        precio: "$4.055",
        tipoConstruccion:"En Seco",
    },
    {
        id:15,
        nombre: "Solera 35",
        medida:"50Px12x2.60 m" ,
        marca:"Maxhaus" ,
        precio: "$3.525",
        tipoConstruccion:"En Seco",
    },
    {  id:16,
    nombre: "Masilla",
    medida:"32 kg" ,
    marca:"Anclaflex" ,
    precio: "$19.664",
    tipoConstruccion:"En Seco",
    },
    {
        id:17,
        nombre: "Masilla",
        medida:"7 kg" ,
        marca:"Anclaflex" ,
        precio: "$6.916",
        tipoConstruccion:"En Seco",
    },
    {
        id:18,
        nombre: "Cinta de Papel",
        medida:"0.075 x 50 m" ,
        marca:"Hunter" ,
        precio: "$5.220",
        tipoConstruccion:"En Seco",
    },
    {
        id:19,
        nombre: "Bolsa de Piedra",
        medida:"20 dm3" ,
        marca:"Easy" ,
        precio: "$4.670",
        tipoConstruccion:"Tradicional",
    },
    {
        id:20,
        nombre: "Bolsón de Piedra",
        medida:"1 m3" ,
        marca:"Easy" ,
        precio: "$53.065",
        tipoConstruccion:"En Seco",
    },
]
